const fs=require('fs'),assert=require('assert'),path=require('path');
const root=path.join(__dirname,'..');
const html=fs.readFileSync(path.join(root,'index.html'),'utf8');
const patch=fs.readFileSync(path.join(root,'outlast-v33017-combat-balance.js'),'utf8');
const authority=fs.readFileSync(path.join(root,'outlast-v327108-rarity-card-authority.js'),'utf8');
assert.match(html,/outlast-v33017-combat-balance\.js\?v=3\.30\.17/);
assert.match(html,/outlast-v33016-map-layout\.js\?v=3\.30\.16"><\/script><script src="outlast-v33017-combat-balance\.js\?v=3\.30\.17/);
assert.match(patch,/const BALANCED_MULT=.*Mythic:2\.7/);
assert.match(patch,/DroneSwarm.*MineLayer.*ArcBlade.*OmegaBlade.*WastelandBow.*NovaCannon.*RiftBlade.*StormBow/);
assert.match(patch,/PLAYER.*ENEMY.*BOSS.*XP.*COIN.*POWERUP.*SHRINE.*OBJECT/);
assert.match(html,/visualProjectileScale=\(weapon==='Laser'\|\|weapon==='FrostNova'\)\?\.18:1/);
assert.match(authority,/Common:\[[^\]]*Upgrade Luck/);
console.log('v3.30.17 combat balance regression test passed');
