const fs=require('fs'),assert=require('assert'),path=require('path');
const root=path.join(__dirname,'..');
const html=fs.readFileSync(path.join(root,'index.html'),'utf8');
const patch=fs.readFileSync(path.join(root,'outlast-v33017-combat-balance.js'),'utf8');
const authority=fs.readFileSync(path.join(root,'outlast-v327108-rarity-card-authority.js'),'utf8');
assert(html.includes('outlast-v33016-map-layout.js?v=3.30.16</script>'),'map layout layer must be present');
assert(html.includes('outlast-v33017-combat-balance.js?v=3.30.17</script>'),'combat balance layer must be present');
assert(html.indexOf('outlast-v33016-map-layout.js?v=3.30.16') < html.indexOf('outlast-v33017-combat-balance.js?v=3.30.17'),'map layout must load before combat balance');
assert.match(html,/outlast-v33017-final/);
assert.doesNotMatch(html,/outlast-v33017-final>[\s\S]*outlast-v33016/);
assert.match(patch,/Mythic:2\.7/);
assert.match(patch,/DroneSwarm.*MineLayer.*ArcBlade.*OmegaBlade.*WastelandBow.*NovaCannon.*RiftBlade.*StormBow/);
assert.match(patch,/PLAYER.*ENEMY.*BOSS.*XP.*COIN.*POWERUP.*SHRINE.*OBJECT/);
assert.match(html,/visualProjectileScale=\(weapon==='Laser'\|\|weapon==='FrostNova'\)\?\.18:1/);
assert.match(authority,/Common:\[[^\]]*Upgrade Luck/);
console.log('v3.30.17 combat balance regression test passed');
