const fs=require('fs'),assert=require('assert'),path=require('path'),vm=require('vm');
const root=path.join(__dirname,'..'),html=fs.readFileSync(path.join(root,'index.html'),'utf8'),system=fs.readFileSync(path.join(root,'outlast-v3370-game-systems.js'),'utf8'),library=fs.readFileSync(path.join(root,'outlast-v33015-upgrade-library.js'),'utf8');
assert(html.includes('<meta name="outlast-build" content="3.37.5">'),'current metadata');
assert(html.includes("const BUILD='3.37.5',ACK='outlast_update_ack_v3.37.5'"),'mandatory update');
assert(html.includes('v3.37.5 • SURVIVOR HUB')&&html.includes('v3.37.5 — Strict Rarity Ladder + Boss Spawn Reliability'),'release marker and log');
assert(!html.includes('id="coreBtn"')&&!system.includes("['progressCore37','🧩 12 Core Systems','core']"),'remove the one-button core hub');
assert(system.includes("weaponBtn:'combat'")&&system.includes("codexBtn:'enemies'")&&system.includes("worldBossBtn:'bosses'")&&system.includes("mapBtn:'world'")&&system.includes("shopBtn:'economy'")&&system.includes("missionBtn:'objectives'"),'route core content into existing feature areas');
assert(system.includes("const VERSION='3.37.5';")&&library.includes("const V='3.37.5';"),'runtime script versions');
assert(system.includes('Divine:4,Celestial:5,Transcendent:6,Eternal:7,Omega:8'),'preserve high rarity multipliers');
assert(html.includes('const bossAlive=outlastBossIsAlive();')&&html.includes("===0?20:Math.max(30,Math.min(45,Number(game.stats&&game.stats.bossEvery)||40))"),'boss scheduler cadence');
assert(html.includes('if(game)game.activeBossId=null;')&&html.includes('game.bossCount=(Number(game.bossCount)||0)+1;'),'clear stale locks and count each spawn');
assert(!html.includes('if(spawnBoss())game.bossCount=(game.bossCount||0)+1'),'no double boss count');
const tiers=['Common','Uncommon','Rare','Epic','Legendary','Mythic','Divine','Celestial','Transcendent','Eternal','Omega'],mult=[1,1.15,1.35,1.6,1.9,2.25,4,5,6,7,8],pools=Object.fromEntries(tiers.map(t=>[t,[]]));
const doc={readyState:'complete',title:'',querySelectorAll:()=>[],querySelector:()=>null,addEventListener:()=>{},getElementById:()=>null,head:{appendChild:()=>{}},body:{classList:{toggle:()=>{}},appendChild:()=>{}},documentElement:{classList:{toggle:()=>{}},dataset:{}}};
const s={window:{OUTLAST_UPGRADE_RARITY_POOLS:pools,OUTLAST_UPGRADE_RARITY_BY_NAME:{}},document:doc,tempUp:[],game:{player:{}},save:{records:{}},run:{kills:0},helpArticles:[],upgradeRarities:{},setTimeout:()=>{},setInterval:()=>{},console,outlastGrantTempShield:v=>{s.shieldSeconds=v;}};s.window.window=s.window;
vm.runInNewContext(library,s,{timeout:1500});assert.strictEqual(s.tempUp.length,220);for(const t of tiers)assert.strictEqual(pools[t].length,20,t);assert.deepStrictEqual(mult.map(v=>s.window.OUTLAST_UPGRADE_TIER_INTEGER(1,v)),[1,2,3,4,5,6,7,8,9,10,11]);
const cut=system.indexOf('\nfunction zombieAISeed37');assert(cut>0);vm.runInNewContext(system.slice(0,cut)+'\n})();',s,{timeout:1500});const upgrade=s.window.OUTLAST_UPGRADE_BASE37;assert.strictEqual(typeof upgrade,'function');
function p(){return {damage:0,fireRate:.45,max:100,hp:100,speed:300,speedCap:500,magnet:0,regen:0,pierce:0,multiShot:0,range:0,projectileSpeed:1,crit:0,coinMult:1,xpBonus:1,armorPierce:0,bossMult:1,ultDamage:1,healMult:1,upgradeLuck:0,lootLuck:0,treasureLuck:0,shield:0,chain:1,vampire:0,bulletSize:1,slowPower:1,armor:1,critMult:1.8,effects:[]};}
function apply(name,tier){s.game.player=p();s.game.effects=[];s.shieldSeconds=0;const o=upgrade(name,()=>'',()=>{},tier);o.apply();return {desc:String(o.desc),p:s.game.player,shield:Number(s.shieldSeconds)||0};}
const cases=[['Power Shot',x=>x.p.damage],['Rapid Fire',x=>1/x.p.fireRate],['Vitality',x=>x.p.max-100],['Second Heart',x=>x.p.max-100],['Swift Feet',x=>x.p.speed-300],['Magnet',x=>x.p.magnet],['Regeneration',x=>x.p.regen],['Second Wind',x=>x.p.regen],['Piercing',x=>x.p.pierce],['Multi-Shot',x=>x.p.multiShot],['XP Boost',x=>x.p.xpBonus-1],['XP Burst',x=>x.p.xpBonus-1],['Crit Chance',x=>x.p.crit],['Lucky Coins',x=>x.p.coinMult-1],['Adrenaline',x=>x.p.adrenalineSpeedBonus],['Shield Core',x=>x.shield],['Poison Rounds',x=>x.p.poisonDpsMultiplier],['Poison Rounds',x=>x.p.poisonDuration],['Stun Rounds',x=>x.p.stunChance],['Stun Rounds',x=>x.p.stunDuration],['Double Tap',x=>x.p.doubleTapChance],['Lucky Hunter',x=>x.p.luckyXpChance],['Treasure Radar',x=>x.p.treasureDropMultiplier],['Shockwave',x=>x.p.shockwaveRadius],['Shockwave',x=>1/x.p.shockwaveEvery],['Upgrade Luck',x=>x.p.upgradeLuck],['Fortune',x=>x.p.lootLuck],['Treasure Luck',x=>x.p.treasureLuck],['Overheat',x=>1/x.p.fireRate],['Rift Pierce',x=>x.p.pierce],['Coin Magnetism',x=>x.p.magnet],['Heavy Impact',x=>x.p.damage],['Emergency Shield',x=>x.shield],['XP Hunter',x=>x.p.xpBonus-1],['Combat Medic',x=>x.p.regen],['Bloodrush',x=>x.p.berserkDamageBonus],['Fortress',x=>x.p.max-100],['Fortress',x=>1-x.p.armor],['Adrenal Core',x=>x.p.speed-300],['Salvager',x=>x.p.magnet],['XP Reactor',x=>x.p.xpBonus-1],['Quick Reload',x=>1/x.p.fireRate],['Ricochet',x=>x.p.pierce],['Executioner',x=>x.p.executioner],['Bossbreaker',x=>x.p.bossDamageBonus],['Cryo Burst',x=>x.p.frostAuraRadius],['Chain Reaction',x=>x.p.chain-1],['Shock Circuit',x=>x.p.chain-1],['Vampire Core',x=>x.p.vampire],['Lucky Barrage',x=>x.p.doubleTapChance],['Shield Nova',x=>x.shield],['Overclock',x=>x.p.damage],['Last Stand',x=>x.p.lastStandBonus],['Treasure Engine',x=>x.p.treasureDropMultiplier],['Deadly Precision',x=>x.p.crit],['Armor Pierce',x=>x.p.armorPierce],['Frost Aura',x=>x.p.frostAuraRadius],['Cryo Core',x=>x.p.slowPower-1]];
for(const [name,metric] of cases){const vals=tiers.map(t=>metric(apply(name,t)));for(let i=1;i<vals.length;i++)assert(vals[i]>vals[i-1],name+' must increase at '+tiers[i]);}
const families=[['Might 01',p=>p.damage],['Haste 02',p=>1/p.fireRate],['Vital Core 03',p=>p.max-100],['Fleet 04',p=>p.speed-300],['Magnet 05',p=>p.magnet],['Renewal 06',p=>p.regen],['Breach 07',p=>p.pierce],['Volley 08',p=>p.multiShot],['Velocity 09',p=>p.projectileSpeed-1],['Deadeye 10',p=>p.crit],['Fortune 11',p=>p.coinMult-1],['Scholar 12',p=>p.xpBonus-1],['Piercer 13',p=>p.armorPierce],['Bossbane 14',p=>p.bossMult-1],['Arcane 15',p=>p.ultDamage-1],['Medic 16',p=>p.healMult-1],['Luck 17',p=>p.upgradeLuck],['Cache 18',p=>p.lootLuck],['Treasure 19',p=>p.treasureLuck],['Aegis 20',p=>p.shield]];
for(const [name,metric] of families){const vals=tiers.map((t,i)=>{const card=s.tempUp.find(x=>x&&x[0]===t+' '+name);assert(card,'missing '+t+' '+name);s.game.player=p();const d=String(card[1](mult[i]));const result=card[2](mult[i]);if(typeof result==='function')result();return {value:metric(s.game.player),desc:d};});for(let i=1;i<vals.length;i++)assert(vals[i].value>vals[i-1].value,name+' applied effect ties at '+tiers[i]);}
console.log('OUTLAST v3.37.5 rarity, boss reliability, and core placement checks passed');
