const fs=require('fs'),assert=require('assert');
const html=fs.readFileSync('index.html','utf8');
const patch=fs.readFileSync('outlast-v3360-system-fixes.js','utf8');
assert(html.includes('outlast-v3360-system-fixes.js'),'v3.36 client patch must be loaded by the game');
assert(patch.includes('outlast-v3360-mandatory-update')&&patch.includes('/api/version'),'mandatory update check must be present');
assert(patch.includes('OUTLAST_INRUN_RARITIES'),'authoritative in-run rarity profiles must be exposed');
assert(patch.includes("Common:{mult:1")&&patch.includes("Mythic:{mult:2.25")&&patch.includes("Omega:{mult:5.5"),'rarity ladder must materially scale effects');
assert(patch.includes('const m=(RARITIES[rarity]||RARITIES.Common).mult'),'upgrade choices must derive boosts from actual rarity');
assert(html.includes("outlastTakePlayerDamage(p,actual*dt,'enemy contact')"),'contact damage must use shield/damage routing');
assert(patch.includes('window.__v3360BossSequence')&&patch.includes('if(liveBoss())'),'a second boss must be blocked while one is alive');
assert(html.includes("const byRarity={Common:[],Uncommon:[],Rare:[],Epic:[],Legendary:[],Mythic:[],Divine:[],Celestial:[],Transcendent:[],Eternal:[],Omega:[],Special:[]}"),'all skin rarities must be safe in the skin menu');
assert(!html.includes('id="ownerRemakePassword"')&&patch.includes("const OWNER_NAMES=new Set(['bestgamer','landon','phone landon','poke','billybimbo'])"),'owner UI must be passwordless and owner-gated');
assert(patch.includes('const CORE=[')&&(patch.match(/\['[^']+','[^']+','[^']+'\]/g)||[]).length>=12,'12 core systems must be player-facing');
assert(patch.includes('const EXTRA=[')&&patch.includes('function enhancedStats()')&&patch.includes('const EXTRA_SHOP=[')&&patch.includes('function inventoryPlus()')&&patch.includes('function modifierPlus()'),'expanded Progress/Stats/Shop/Inventory/Modifiers must ship');
assert(patch.includes('v3.36.0 — System & Balance Fixes'),'the update log entry must ship');
console.log('OUTLAST v3.36 client regression checks passed');
