const fs=require('fs'),assert=require('assert');
const html=fs.readFileSync('index.html','utf8');
const patch=fs.readFileSync('outlast-v3360-system-fixes.js','utf8');
assert(html.includes('outlast-v3360-system-fixes.js'),'v3.36 client patch must be loaded by the game');
assert(patch.includes('outlast-v3360-mandatory-update')&&patch.includes('/api/version'),'mandatory server update check must be present');
assert(patch.includes('OUTLAST_INRUN_RARITIES'),'authoritative in-run rarity profiles must be exposed');
assert(patch.includes("Common:{mult:1")&&patch.includes("Mythic:{mult:2.25")&&patch.includes("Omega:{mult:5.5"),'rarity multipliers must scale across the rarity ladder');
assert(patch.includes('const m=(RARITIES[rarity]||RARITIES.Common).mult'),'upgrade cards must derive their effect multiplier from their actual rarity');
assert(html.includes("outlastTakePlayerDamage(p,actual*dt,'enemy contact')"),'enemy contact damage must pass through the shield/damage gate');
assert(patch.includes('window.__v3360BossSequence')&&patch.includes('if(liveBoss())'),'boss sequence guard must block a second live boss');
assert(html.includes("const byRarity={Common:[],Uncommon:[],Rare:[],Epic:[],Legendary:[],Mythic:[],Divine:[],Celestial:[],Transcendent:[],Eternal:[],Omega:[],Special:[]}"),'skin menu must support every skin rarity without crashing');
assert(html.includes('ownerPanelCard')&&!html.includes('id="ownerRemakePassword"'),'owner panel must be owner-gated and password UI removed');
assert(patch.includes("const OWNER_NAMES=new Set(['bestgamer','landon','phone landon','poke','billybimbo'])"),'owner allowlist must include the configured owner accounts');
assert(patch.includes("const CORE=[")&&patch.match(/\['[^']+','[^']+','[^']+'\]/g)?.length>=12,'12 Core Systems must be exposed to the player');
assert(patch.includes("v3360Achievements")||patch.includes("EXTRA=["),'expanded achievements must ship');
assert(patch.includes('function enhancedStats()'),'expanded stats must ship');
assert(patch.includes('const EXTRA_SHOP=['),'expanded Daily Shop must ship');
assert(patch.includes('function inventoryPlus()'),'cleaned Inventory must ship');
assert(patch.includes('function modifierPlus()'),'expanded Run Modifiers must ship');
assert(patch.includes('v3.36.0 — System & Balance Fixes'),'Update Log entry must ship');
console.log('OUTLAST v3.36 client regression checks passed');
