const fs=require('fs'),assert=require('assert');
const html=fs.readFileSync('index.html','utf8');
assert(html.includes('outlast-v3360-mandatory-update'),'mandatory update gate must be present');
assert(html.includes('/api/version'),'client must check the authoritative server version');
assert(html.includes('OUTLAST_INRUN_RARITIES'),'authoritative in-run rarity profiles must be exposed');
assert(html.includes("Common:{mult:1") && html.includes("Mythic:{mult:3"),'rarity multipliers must be materially different');
assert(html.includes('outlastTakePlayerDamage(p,actual*dt'),'enemy contact damage must pass through the shield/damage gate');
assert(html.includes('outlast-v3360-boss-sequence'),'boss sequencing regression fix must be installed');
assert(html.includes('if(hasLiveBoss())return false'),'boss spawns must be blocked while a boss is alive');
assert(html.includes('ownerPanelCard') && html.includes('isOwner()'),'owner panel visibility must be owner-gated');
assert(!html.includes('id="ownerRemakePassword"'),'owner UI must not request a password');
assert(html.includes('outlast-v3360-skin-fix'),'skin selection/runtime sync fix must be installed');
assert(html.includes('12 Core Systems') && html.includes('core-system-grid'),'12 core systems must be player-facing in Progress');
assert(html.includes('outlast-v3360-achievements'),'expanded achievements must be installed');
assert(html.includes('outlast-v3360-stats'),'expanded stats must be installed');
assert(html.includes('outlast-v3360-shop'),'expanded daily shop must be installed');
assert(html.includes('outlast-v3360-inventory'),'cleaned inventory UI must be installed');
assert(html.includes('outlast-v3360-modifiers'),'expanded run modifiers UI must be installed');
console.log('OUTLAST v3.36 regression checks passed');
